<?php
require_once __DIR__ . '/../includes/helpers.php'; require_auth(); $pdo=db(); $id=(int)($_GET['id']??0); $student=student_by_id($id); if(!$student) exit('Aluno não encontrado.');
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf(); if(($_POST['action']??'')==='delete'){ $pdo->prepare('DELETE FROM evaluations WHERE id=? AND student_id=?')->execute([(int)$_POST['row_id'],$id]); } else { $pdo->prepare('INSERT INTO evaluations(student_id,evaluation_date,coordination,balance,agility,strength,endurance,confidence,notes) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$id,$_POST['evaluation_date'],(int)$_POST['coordination'],(int)$_POST['balance'],(int)$_POST['agility'],(int)$_POST['strength'],(int)$_POST['endurance'],(int)$_POST['confidence'],trim((string)$_POST['notes'])]); } redirect('avaliacoes.php?id='.$id); }
$stmt=$pdo->prepare('SELECT * FROM evaluations WHERE student_id=? ORDER BY evaluation_date DESC,id DESC');$stmt->execute([$id]);$rows=$stmt->fetchAll();
include __DIR__.'/../includes/admin_header.php';
?>
<div class="admin-content"><div class="page-head"><div><h1>Avaliações — <?= e($student['name']) ?></h1><p>Escala interna de 1 a 10 para acompanhar evolução. Não constitui diagnóstico clínico.</p></div><a class="btn btn-light" href="aluno.php?id=<?= $id ?>">← Ficha do aluno</a></div>
<section class="panel"><h2>Nova avaliação</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label>Data<input required type="date" name="evaluation_date" value="<?= date('Y-m-d') ?>"></label><div></div><?php foreach(['coordination'=>'Coordenação','balance'=>'Equilíbrio','agility'=>'Agilidade','strength'=>'Força funcional','endurance'=>'Resistência','confidence'=>'Participação / confiança'] as $key=>$label):?><label><?= e($label) ?><input required type="number" name="<?= e($key) ?>" min="1" max="10" value="5"></label><?php endforeach;?><label class="full">Observações<textarea name="notes" rows="4"></textarea></label><div class="full"><button class="btn btn-primary">Salvar avaliação</button></div></form></section>
<?php foreach($rows as $r):?><section class="panel"><div class="page-head" style="margin-bottom:10px"><div><h2 style="margin:0">Avaliação de <?= e(date('d/m/Y',strtotime($r['evaluation_date']))) ?></h2></div><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="row_id" value="<?= (int)$r['id'] ?>"><button class="btn btn-danger" data-confirm="Excluir esta avaliação?">Excluir</button></form></div><div class="chart-bars"><?php foreach(['coordination'=>'Coordenação','balance'=>'Equilíbrio','agility'=>'Agilidade','strength'=>'Força','endurance'=>'Resistência','confidence'=>'Confiança'] as $key=>$label):?><div class="chart-row"><span><?= e($label) ?></span><div class="chart-track"><div class="chart-fill" style="width:<?= (int)$r[$key]*10 ?>%"></div></div><strong><?= (int)$r[$key] ?>/10</strong></div><?php endforeach;?></div><?php if($r['notes']):?><p><?= nl2br(e($r['notes'])) ?></p><?php endif;?></section><?php endforeach;?>
<?php if(!$rows):?><section class="panel">Nenhuma avaliação registrada.</section><?php endif;?></div>
<?php include __DIR__.'/../includes/admin_footer.php';?>
