<?php
require_once __DIR__ . '/../includes/helpers.php'; require_auth(); $pdo=db(); $id=(int)($_GET['id']??0); $student=student_by_id($id); if(!$student) exit('Aluno não encontrado.');
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf(); if(($_POST['action']??'')==='delete'){ $pdo->prepare('DELETE FROM attendance WHERE id=? AND student_id=?')->execute([(int)$_POST['row_id'],$id]); } else { $pdo->prepare('INSERT INTO attendance(student_id,class_date,duration_minutes,present,activity,notes) VALUES(?,?,?,?,?,?)')->execute([$id,$_POST['class_date'],(int)$_POST['duration_minutes'],isset($_POST['present'])?1:0,trim((string)$_POST['activity']),trim((string)$_POST['notes'])]); } redirect('frequencia.php?id='.$id); }
$rows=$pdo->prepare('SELECT * FROM attendance WHERE student_id=? ORDER BY class_date DESC,id DESC'); $rows->execute([$id]); $rows=$rows->fetchAll(); $stats=attendance_stats($id);
include __DIR__.'/../includes/admin_header.php';
?>
<div class="admin-content"><div class="page-head"><div><h1>Frequência — <?= e($student['name']) ?></h1><p>Registro das aulas realizadas.</p></div><a class="btn btn-light" href="aluno.php?id=<?= $id ?>">← Ficha do aluno</a></div><div class="metric-grid"><div class="metric"><span>Aulas</span><strong><?= $stats['total'] ?></strong></div><div class="metric"><span>Presenças</span><strong><?= $stats['present'] ?></strong></div><div class="metric"><span>Faltas</span><strong><?= $stats['absent'] ?></strong></div><div class="metric"><span>Frequência</span><strong><?= $stats['percent'] ?>%</strong></div></div>
<section class="panel"><h2>Registrar aula</h2><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label>Data<input required type="date" name="class_date" value="<?= date('Y-m-d') ?>"></label><label>Duração (minutos)<input required type="number" min="10" max="240" name="duration_minutes" value="60"></label><label class="full">Atividade<input name="activity" placeholder="Ex.: coordenação, circuito, preparação esportiva"></label><label><input type="checkbox" name="present" checked style="width:auto;margin-right:7px">Presente</label><label class="full">Observação<textarea name="notes" rows="3"></textarea></label><div class="full"><button class="btn btn-primary">Salvar aula</button></div></form></section>
<section class="panel"><h2>Histórico</h2><div class="table-wrap"><table><thead><tr><th>Data</th><th>Atividade</th><th>Duração</th><th>Status</th><th>Observação</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6">Nenhuma aula registrada.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td><?= e(date('d/m/Y',strtotime($r['class_date']))) ?></td><td><?= e($r['activity']?:'—') ?></td><td><?= (int)$r['duration_minutes'] ?> min</td><td><span class="badge <?= $r['present']?'':'off' ?>"><?= $r['present']?'Presente':'Falta' ?></span></td><td><?= e($r['notes']?:'—') ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="row_id" value="<?= (int)$r['id'] ?>"><button class="btn btn-danger" data-confirm="Excluir este registro?">Excluir</button></form></td></tr><?php endforeach;?></tbody></table></div></section></div>
<?php include __DIR__.'/../includes/admin_footer.php';?>
